In [1]:
import time
from sklearn.neural_network import MLPClassifier
from sklearn import datasets, preprocessing
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [2]:
bc = datasets.load_breast_cancer()

In [3]:
bc_df = pd.DataFrame(bc.data, columns=bc.feature_names)

In [4]:
bc_df['output'] = bc.target

In [5]:
corr = bc_df.corr()

In [6]:
corr.sort_values(by='output')[:2]

mean radius  mean texture  mean perimeter  mean area  \
worst concave points     0.744214      0.295316        0.771241   0.722017   
worst perimeter          0.965137      0.358040        0.970387   0.959120   

                      mean smoothness  mean compactness  mean concavity  \
worst concave points         0.503053          0.815573        0.861323   
worst perimeter              0.238853          0.590210        0.729565   

                      mean concave points  mean symmetry  \
worst concave points             0.910155       0.430297   
worst perimeter                  0.855923       0.219169   

                      mean fractal dimension    ...     worst texture  \
worst concave points                0.175325    ...          0.359755   
worst perimeter                    -0.205151    ...          0.365098   

                      worst perimeter  worst area  worst smoothness  \
worst concave points         0.816322    0.747419          0.547691   
worst perimeter              1.000000    0.977578          0.236775   

                      worst compactness  worst concavity  \
worst concave points           0.801080         0.855434   
worst perimeter                0.529408         0.618344   

                      worst concave points  worst symmetry  \
worst concave points              1.000000        0.502528   
worst perimeter                   0.816322        0.269493   

                      worst fractal dimension    output  
worst concave points                 0.511114 -0.793566  
worst perimeter                      0.138957 -0.782914  

[2 rows x 31 columns]

In [7]:
print(bc.DESCR)

Breast Cancer Wisconsin (Diagnostic) Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, field
        13 is Radius SE, field 23 is Worst Radius.

        

In [8]:
y1 = np.matrix([np.array(bc.target == 0),np.array(bc.target == 1)]).transpose()
y1.shape

(569, 2)

In [9]:
X = preprocessing.normalize(bc_df[['worst concave points','worst perimeter']],axis=1)  
# we only take the first two features.

In [10]:
X

array([[ 0.0014377 ,  0.99999897],
       [ 0.00117128,  0.99999931],
       [ 0.00159344,  0.99999873],
       ..., 
       [ 0.00111918,  0.99999937],
       [ 0.00143553,  0.99999897],
       [ 0.        ,  1.        ]])

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y1, test_size=0.20, random_state=42)

In [12]:
clf = MLPClassifier(solver='adam', max_iter=1, warm_start=True,
                    hidden_layer_sizes=(3),random_state=42)

In [13]:
from rgb_nn import RGB_NN

In [14]:
conn = RGB_NN('saja')

In [15]:
c = None
for i in range(10):
    clf.fit(X_train, y_train)
    print(clf.score(X_test, y_test))
    print(conn.display_weights(clf))

0.0
val: -0.273635021605
val: -0.273635021605
val: 0.990464095545
val: 0.990464095545
val: 0.506632284665
val: 0.506632284665
val: 0.215069631034
val: 0.215069631034
val: -0.750622457449
val: -0.750622457449
val: -0.751786629897
val: -0.751786629897
val: 0.454295049441
val: 0.454295049441
val: -1.04826293436
val: -1.04826293436
val: 1.03227362593
val: 1.03227362593
val: 0.731332924727
val: 0.731332924727
val: -0.628453279569
val: -0.628453279569
val: -0.695243020754
val: -0.695243020754
val: -0.968190296587
val: -0.968190296587
val: 0.805254682634
val: 0.805254682634
val: 0.221531891337
val: 0.221531891337
val: -0.690905600054
val: -0.690905600054
val: -0.425903660297
val: -0.425903660297
{'leds': [{'led_num': 5, 'green': 0, 'red': 91, 'blue': 255}, {'led_num': 11, 'green': 0, 'red': 91, 'blue': 255}, {'led_num': 6, 'green': 0, 'red': 255, 'blue': 14}, {'led_num': 20, 'green': 0, 'red': 255, 'blue': 14}, {'led_num': 7, 'green': 244, 'red': 0, 'blue': 255}, {'led_num': 28, 'green': 244,

/Users/zackakil/anaconda/envs/dev/lib/python3.5/site-packages/sklearn/neural_network/multilayer_perceptron.py:563: ConvergenceWarning: Stochastic Optimizer: Maximum iterations reached and the optimization hasn't converged yet.
  % (), ConvergenceWarning)


In [16]:
clf.coefs_

[array([[-0.26266315,  1.017419  ,  0.49195968],
        [ 0.20548813, -0.72363631, -0.7348315 ]]),
 array([[ 0.4402764 , -1.02955769],
        [ 1.05807208,  0.75836397],
        [-0.61251334, -0.67872566]])]

In [17]:
X_train

array([[  2.67174619e-03,   9.99996431e-01],
       [  1.64475698e-03,   9.99998647e-01],
       [  7.75575312e-04,   9.99999699e-01],
       [  7.86868184e-04,   9.99999690e-01],
       [  3.69166880e-04,   9.99999932e-01],
       [  1.37953132e-03,   9.99999048e-01],
       [  1.00393263e-03,   9.99999496e-01],
       [  1.06042728e-03,   9.99999438e-01],
       [  9.48151999e-04,   9.99999551e-01],
       [  1.00498392e-03,   9.99999495e-01],
       [  1.31751471e-03,   9.99999132e-01],
       [  1.35552789e-03,   9.99999081e-01],
       [  1.59480521e-03,   9.99998728e-01],
       [  9.25507504e-04,   9.99999572e-01],
       [  7.45200305e-04,   9.99999722e-01],
       [  1.10594728e-03,   9.99999388e-01],
       [  1.43770166e-03,   9.99998967e-01],
       [  1.83061076e-03,   9.99998324e-01],
       [  7.11720047e-04,   9.99999747e-01],
       [  7.09465961e-04,   9.99999748e-01],
       [  9.10289860e-04,   9.99999586e-01],
       [  1.91286620e-03,   9.99998170e-01],
       [  

In [19]:
conn._val_to_rgb(0.1)

val: 0.1


[255, 153, 0]