In [1]:
from sklearn.neural_network import MLPClassifier
from sklearn import datasets, preprocessing
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [2]:
iris = datasets.load_iris()

In [3]:
X = preprocessing.normalize(iris.data[:, :2],axis=1)  # we only take the first two features.
y = iris.target

In [4]:
mask = y != 2
X = X[mask]
y = y[mask]

In [5]:
y == 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False, False], dtype=bool)

In [6]:
y1 = np.matrix([np.array(y == 0),np.array(y == 1)]).transpose()

In [7]:
y1.shape, X.shape

((100, 2), (100, 2))

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y1, test_size=0.33, random_state=42)

In [9]:
clf = MLPClassifier(solver='lbfgs', max_iter=1, warm_start=True,
                    hidden_layer_sizes=(3), random_state=1)

In [10]:
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.42424242424242425

In [11]:
clf.coefs_[0].shape, clf.coefs_[1].shape

((2, 3), (3, 2))

In [12]:
clf.coefs_[0]

array([[-0.18179391,  0.48270209, -1.09518389],
       [-0.43306343, -0.77391155, -0.89313271]])

In [13]:
clf.coefs_[1]

array([[ 0.08504238, -0.17703423],
       [ 0.40579165, -0.64750639],
       [ 0.82840575, -1.03543185]])

In [14]:
clf.intercepts_[0].shape, clf.intercepts_[1].shape

((3,), (2,))

In [15]:
clf.intercepts_

[array([-0.68736944, -0.33835949, -0.22617113]),
 array([-0.47017521,  0.35571616])]

In [111]:
# %%writefile led_map.py

def unwrap_to_pairs(l):
    o = []
    if type(l[0]) == list:
        for i in l:
            x = unwrap_to_pairs(i)
            if type(x[0]) != list:
                o += [x]
            else:
                o += x
        return o
    else:
        print(l)
        return l

input_layer_bias = [
                    [8,9],
                    [3,4]
                    ]

input_layer_weights = [
                        [[5,11],[6,20],[7,28]],
                        [[0,10],[1,18],[2,27]]
                        
                      ]

hidden_layer_bias = [
                        [13,14],
                        [21,22],
                        [29,30]
                    ]

hidden_layer_weights = [
                            [[16,41],[15,36]],
                            [[23,40],[25,35]],
                            [[31,39],[32,34]]
                       ]

output_layer_bias = [
                        [42,43],
                        [37,38]
                    ]

weight_index =  (unwrap_to_pairs(input_layer_weights) + 
                 unwrap_to_pairs(hidden_layer_weights)
                )

bias_index =    (input_layer_bias +
                 hidden_layer_bias +
                 output_layer_bias)

import colorsys

def val_to_rgb(val):
    i = val*0.67
    c = colorsys.hsv_to_rgb(i,1,1)
    return [int(color*255) for color in c]

def map_weight_to_led(coefs, led_map):
    leds = []
    for i,v in enumerate(led_map):
        for i2,v2 in enumerate(v):
            print(i,i2,v2,coefs[i][i2])
            
            for led in v2:
                colours = val_to_rgb(coefs[i][i2])
                leds.append({"led_num":led,"red": colours[0], "green": colours[1], "blue": colours[2],})
    return leds

def map_bias_to_led(bias, led_map):
    leds = []
    for i,v in enumerate(led_map):
        print(i,v,bias[i])
        for led in v:
            leds.append({"led_num":led, "val":bias[i]})
    return leds

def make_led_coef_vals(clf):
    leds = []
    leds += map_weight_to_led(clf.coefs_[0], input_layer_weights)
    leds += map_weight_to_led(clf.coefs_[1], hidden_layer_weights)
    leds += map_bias_to_led(clf.intercepts_[0], hidden_layer_bias)
    leds += map_bias_to_led(clf.intercepts_[0], output_layer_bias)
    return leds

[5, 11]
[6, 20]
[7, 28]
[0, 10]
[1, 18]
[2, 27]
[16, 41]
[15, 36]
[23, 40]
[25, 35]
[31, 39]
[32, 34]


In [112]:
map_weight_to_led(coefs, led_map)

NameError: name 'coefs' is not defined

In [113]:
bias_index

[[8, 9], [3, 4], [13, 14], [21, 22], [29, 30], [42, 43], [37, 38]]

In [114]:
map_weight_to_led(clf.coefs_[1], hidden_layer_weights)

0 0 [16, 41] 0.0850423770945
0 1 [15, 36] -0.177034229022
1 0 [23, 40] 0.405791651524
1 1 [25, 35] -0.647506387982
2 0 [31, 39] 0.828405749149
2 1 [32, 34] -1.03543184533


[{'blue': 0, 'green': 87, 'led_num': 16, 'red': 255},
 {'blue': 0, 'green': 87, 'led_num': 41, 'red': 255},
 {'blue': 0, 'green': -181, 'led_num': 15, 'red': 255},
 {'blue': 0, 'green': -181, 'led_num': 36, 'red': 255},
 {'blue': 0, 'green': 255, 'led_num': 23, 'red': 94},
 {'blue': 0, 'green': 255, 'led_num': 40, 'red': 94},
 {'blue': 255, 'green': 0, 'led_num': 25, 'red': -153},
 {'blue': 255, 'green': 0, 'led_num': 35, 'red': -153},
 {'blue': 255, 'green': 170, 'led_num': 31, 'red': 0},
 {'blue': 255, 'green': 170, 'led_num': 39, 'red': 0},
 {'blue': -41, 'green': 255, 'led_num': 32, 'red': 0},
 {'blue': -41, 'green': 255, 'led_num': 34, 'red': 0}]

In [110]:
map_bias_to_led(clf.intercepts_[0],hidden_layer_bias)

0 [13, 14] -0.687369437661
1 [21, 22] -0.338359494253
2 [29, 30] -0.226171132128


[{'led_num': 13, 'val': -0.68736943766140923},
 {'led_num': 14, 'val': -0.68736943766140923},
 {'led_num': 21, 'val': -0.33835949425288125},
 {'led_num': 22, 'val': -0.33835949425288125},
 {'led_num': 29, 'val': -0.22617113212838169},
 {'led_num': 30, 'val': -0.22617113212838169}]

In [107]:
f = make_led_coef_vals(clf)
sorted(f, key=lambda k: k['led_num']) 

0 0 [5, 11] -0.181793913059
0 1 [6, 20] 0.48270209062
0 2 [7, 28] -1.09518389253
1 0 [0, 10] -0.433063428162
1 1 [1, 18] -0.773911548997
1 2 [2, 27] -0.893132713009
0 0 [16, 41] 0.0850423770945
0 1 [15, 36] -0.177034229022
1 0 [23, 40] 0.405791651524
1 1 [25, 35] -0.647506387982
2 0 [31, 39] 0.828405749149
2 1 [32, 34] -1.03543184533
0 [13, 14] -0.687369437661
1 [21, 22] -0.338359494253
2 [29, 30] -0.226171132128
0 [42, 43] -0.687369437661
1 [37, 38] -0.338359494253


[{'blue': 0, 'green': 85.040485775685298, 'led_num': 0, 'red': 0},
 {'blue': 0, 'green': 33.91326765040246, 'led_num': 1, 'red': 0},
 {'blue': 0, 'green': 16.0300930486741, 'led_num': 2, 'red': 0},
 {'blue': 0, 'green': 122.73091304118169, 'led_num': 5, 'red': 0},
 {'blue': 0, 'green': 222.40531359303844, 'led_num': 6, 'red': 0},
 {'blue': 0, 'green': -14.277583878818067, 'led_num': 7, 'red': 0},
 {'blue': 0, 'green': 85.040485775685298, 'led_num': 10, 'red': 0},
 {'blue': 0, 'green': 122.73091304118169, 'led_num': 11, 'red': 0},
 {'led_num': 13, 'val': -0.68736943766140923},
 {'led_num': 14, 'val': -0.68736943766140923},
 {'blue': 0, 'green': 123.44486564675482, 'led_num': 15, 'red': 0},
 {'blue': 0, 'green': 162.75635656418052, 'led_num': 16, 'red': 0},
 {'blue': 0, 'green': 33.91326765040246, 'led_num': 18, 'red': 0},
 {'blue': 0, 'green': 222.40531359303844, 'led_num': 20, 'red': 0},
 {'led_num': 21, 'val': -0.33835949425288125},
 {'led_num': 22, 'val': -0.33835949425288125},
 {'bl